-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `product` ENUM('SUBSCRIPTION', 'LIFETIME') NOT NULL DEFAULT 'SUBSCRIPTION';

-- CreateTable
CREATE TABLE `CommonAccess` (
    `userId` BIGINT NOT NULL,
    `paidAt` DATETIME(3) NOT NULL,
    `inGroup` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CommonAccess` ADD CONSTRAINT `CommonAccess_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

